configs:
  zero:
    x_data: 0.0
    y_data: 0.0
    yaw: 0.0
  config1:
    x_data: 1.0
    y_data: 0.0
    yaw: 0.5
  config2:
    x_data: 2.0
    y_data: 0.0
    yaw: 0.5
  config4:
    x_data: 1.0
    y_data: -1.0
    yaw: 0.0